### PR TITLE
Added support for an exclude.json file to the Tub class.

### PR DESCRIPTION
**Pull request by Bleyddyn**
Training code will skip any records in the exclude list.

Should have no effect unless you create an exclude.json file in a Tub directory, with a list of indexes to exclude from training.

e.g.
`tub.include_index(1)
tub.include_index(99)
tub.write_exclude()`

### CODE REVIEW

**Comment by tawnkramer** [comment]
curious what this is solving for you? Do you want to non-destructively ignore data rather than delete it?

**Comment by tawnkramer** [comment]
did you know we have controls (Triangle) to delete the last 100 records while driving? This is a very convenient way to remove data you don't want. Doing it in post can be time consuming. But there is a tool to do that too. ```donkey tubclean data```

**Comment by Bleyddyn** [comment]
I do prefer not to delete data. Too many times I've wished I had it back for something different. One example is when I decided to train a lane detector and realized that I'd deleted all of the data I had from inside/outside the track and had to go back and record more.

I've tried tubclean and although it brought up a web page I couldn't get it to do anything at all. I'll try it again with a different web browser.

I have a few issues with the Delete100/Triangle button. I have to remember to use it immediately after I make a mistake, which doesn't happen often, and I have no feel for how much data I'm deleting. It seems to me like it's deleting far too much (although I'll have to look at what I've collected so far to see how much I'm excluding). And, since I'm going to go through all of my data anyway, to correct my bad driving, I might as well exclude data then.

That last point does show that I do things quite a bit differently than most DonkeyCar'ers, so feel free to close anything you don't think will benefit other people.

**Comment by tawnkramer** [comment]
No, that's fine. This does not slow down the most common case. And if it helps you, it may help someone else at some point. Just wanted to make sure you were aware of the options for data management.

the donkey tubclean wants to be pointed to the dir above the tubs. so usually ```donkey tubclean data``` and then browse to different tubs in web ui.

**Pull request merged**
